//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.09.06 at 10:42:47 PM BST 
//


package com.example.howtodoinjava.schemas.school;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AdresBinnenOfBuitenlandsType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AdresBinnenOfBuitenlandsType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;choice&gt;
 *         &lt;element name="binnenlandsAdres" type="{http://schemas.kvk.nl/schemas/hrip/catalogus/2015/02}BinnenlandsAdresType"/&gt;
 *         &lt;element name="buitenlandsAdres" type="{http://schemas.kvk.nl/schemas/hrip/catalogus/2015/02}BuitenlandsAdresType"/&gt;
 *       &lt;/choice&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AdresBinnenOfBuitenlandsType", propOrder = {
    "binnenlandsAdres",
    "buitenlandsAdres"
})
public class AdresBinnenOfBuitenlandsType {

    protected BinnenlandsAdresType binnenlandsAdres;
    protected BuitenlandsAdresType buitenlandsAdres;

    /**
     * Gets the value of the binnenlandsAdres property.
     * 
     * @return
     *     possible object is
     *     {@link BinnenlandsAdresType }
     *     
     */
    public BinnenlandsAdresType getBinnenlandsAdres() {
        return binnenlandsAdres;
    }

    /**
     * Sets the value of the binnenlandsAdres property.
     * 
     * @param value
     *     allowed object is
     *     {@link BinnenlandsAdresType }
     *     
     */
    public void setBinnenlandsAdres(BinnenlandsAdresType value) {
        this.binnenlandsAdres = value;
    }

    /**
     * Gets the value of the buitenlandsAdres property.
     * 
     * @return
     *     possible object is
     *     {@link BuitenlandsAdresType }
     *     
     */
    public BuitenlandsAdresType getBuitenlandsAdres() {
        return buitenlandsAdres;
    }

    /**
     * Sets the value of the buitenlandsAdres property.
     * 
     * @param value
     *     allowed object is
     *     {@link BuitenlandsAdresType }
     *     
     */
    public void setBuitenlandsAdres(BuitenlandsAdresType value) {
        this.buitenlandsAdres = value;
    }

}
