//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.09.06 at 11:14:48 AM BST 
//


package com.example.howtodoinjava.schemas.school;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for BagIdType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="BagIdType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="identificatieNummeraanduiding" type="{http://schemas.kvk.nl/schemas/hrip/catalogus/2015/02}Tekst16"/&gt;
 *         &lt;element name="identificatieAdresseerbaarObject" type="{http://schemas.kvk.nl/schemas/hrip/catalogus/2015/02}Tekst16"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BagIdType", propOrder = {
    "identificatieNummeraanduiding",
    "identificatieAdresseerbaarObject"
})
public class BagIdType {

    @XmlElement(required = true)
    protected String identificatieNummeraanduiding;
    @XmlElement(required = true)
    protected String identificatieAdresseerbaarObject;

    /**
     * Gets the value of the identificatieNummeraanduiding property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIdentificatieNummeraanduiding() {
        return identificatieNummeraanduiding;
    }

    /**
     * Sets the value of the identificatieNummeraanduiding property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIdentificatieNummeraanduiding(String value) {
        this.identificatieNummeraanduiding = value;
    }

    /**
     * Gets the value of the identificatieAdresseerbaarObject property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIdentificatieAdresseerbaarObject() {
        return identificatieAdresseerbaarObject;
    }

    /**
     * Sets the value of the identificatieAdresseerbaarObject property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIdentificatieAdresseerbaarObject(String value) {
        this.identificatieAdresseerbaarObject = value;
    }

}
