//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.09.06 at 10:42:47 PM BST 
//


package com.example.howtodoinjava.schemas.school;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for BasisType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="BasisType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://schemas.kvk.nl/schemas/hrip/catalogus/2015/02}MetExtraElementenMogenlijkheidType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="registratie" type="{http://schemas.kvk.nl/schemas/hrip/catalogus/2015/02}RegistratieType" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BasisType", propOrder = {
    "registratie"
})
@XmlSeeAlso({
    MaatschappelijkeActiviteitType.class,
    OndernemingType.class,
    BeperkingInRechtshandelingType.class,
    BevoegdheidAansprakelijkeType.class,
    BevoegdheidBestuurderType.class,
    BevoegdheidOverigeFunctionarisType.class,
    BevoegdheidPubliekrechtelijkeFunctionarisType.class,
    BevoegdheidBewindvoerderType.class,
    BijzondereRechtstoestandType.class,
    BuitenlandseRechtstoestandType.class,
    RechtspersoonGegevensBuitenlandType.class,
    BuitenlandseRegistratieGegevensType.class,
    BuitenlandseVennootschapGegevensType.class,
    CommanditairKapitaalType.class,
    CommunicatiegegevensType.class,
    DuurType.class,
    FunctietitelType.class,
    HandlichtingType.class,
    KapitaalType.class,
    LocatieType.class,
    SchorsingType.class,
    AandeelSamenstellingType.class,
    AandeelType.class,
    LiquidatieType.class,
    OntbindingType.class,
    SBIActiviteitType.class,
    VoornemenTotOntbindingType.class,
    PersoonType.class,
    FunctievervullingType.class,
    VestigingType.class,
    NaamgevingType.class,
    VolmachtType.class,
    HandelsnaamType.class,
    FusieSplitsingType.class,
    OpTeRichtenRechtspersoonType.class
})
public abstract class BasisType
    extends MetExtraElementenMogenlijkheidType
{

    protected RegistratieType registratie;

    /**
     * Gets the value of the registratie property.
     * 
     * @return
     *     possible object is
     *     {@link RegistratieType }
     *     
     */
    public RegistratieType getRegistratie() {
        return registratie;
    }

    /**
     * Sets the value of the registratie property.
     * 
     * @param value
     *     allowed object is
     *     {@link RegistratieType }
     *     
     */
    public void setRegistratie(RegistratieType value) {
        this.registratie = value;
    }

}
