//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.09.06 at 11:14:48 AM BST 
//


package com.example.howtodoinjava.schemas.school;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for FunctievervullingRelatieType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="FunctievervullingRelatieType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://schemas.kvk.nl/schemas/hrip/catalogus/2015/02}RelatieType"&gt;
 *       &lt;choice&gt;
 *         &lt;element name="aansprakelijke" type="{http://schemas.kvk.nl/schemas/hrip/catalogus/2015/02}AansprakelijkeType"/&gt;
 *         &lt;element name="bestuursfunctie" type="{http://schemas.kvk.nl/schemas/hrip/catalogus/2015/02}BestuursfunctieType"/&gt;
 *         &lt;element name="functionarisBijzondereRechtstoestand" type="{http://schemas.kvk.nl/schemas/hrip/catalogus/2015/02}FunctionarisBijzondereRechtstoestandType"/&gt;
 *         &lt;element name="gemachtigde" type="{http://schemas.kvk.nl/schemas/hrip/catalogus/2015/02}GemachtigdeType"/&gt;
 *         &lt;element name="overigeFunctionaris" type="{http://schemas.kvk.nl/schemas/hrip/catalogus/2015/02}OverigeFunctionarisType"/&gt;
 *         &lt;element name="publiekrechtelijkeFunctionaris" type="{http://schemas.kvk.nl/schemas/hrip/catalogus/2015/02}PubliekrechtelijkeFunctionarisType"/&gt;
 *       &lt;/choice&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FunctievervullingRelatieType", propOrder = {
    "aansprakelijke",
    "bestuursfunctie",
    "functionarisBijzondereRechtstoestand",
    "gemachtigde",
    "overigeFunctionaris",
    "publiekrechtelijkeFunctionaris"
})
public class FunctievervullingRelatieType
    extends RelatieType
{

    protected AansprakelijkeType aansprakelijke;
    protected BestuursfunctieType bestuursfunctie;
    protected FunctionarisBijzondereRechtstoestandType functionarisBijzondereRechtstoestand;
    protected GemachtigdeType gemachtigde;
    protected OverigeFunctionarisType overigeFunctionaris;
    protected PubliekrechtelijkeFunctionarisType publiekrechtelijkeFunctionaris;

    /**
     * Gets the value of the aansprakelijke property.
     * 
     * @return
     *     possible object is
     *     {@link AansprakelijkeType }
     *     
     */
    public AansprakelijkeType getAansprakelijke() {
        return aansprakelijke;
    }

    /**
     * Sets the value of the aansprakelijke property.
     * 
     * @param value
     *     allowed object is
     *     {@link AansprakelijkeType }
     *     
     */
    public void setAansprakelijke(AansprakelijkeType value) {
        this.aansprakelijke = value;
    }

    /**
     * Gets the value of the bestuursfunctie property.
     * 
     * @return
     *     possible object is
     *     {@link BestuursfunctieType }
     *     
     */
    public BestuursfunctieType getBestuursfunctie() {
        return bestuursfunctie;
    }

    /**
     * Sets the value of the bestuursfunctie property.
     * 
     * @param value
     *     allowed object is
     *     {@link BestuursfunctieType }
     *     
     */
    public void setBestuursfunctie(BestuursfunctieType value) {
        this.bestuursfunctie = value;
    }

    /**
     * Gets the value of the functionarisBijzondereRechtstoestand property.
     * 
     * @return
     *     possible object is
     *     {@link FunctionarisBijzondereRechtstoestandType }
     *     
     */
    public FunctionarisBijzondereRechtstoestandType getFunctionarisBijzondereRechtstoestand() {
        return functionarisBijzondereRechtstoestand;
    }

    /**
     * Sets the value of the functionarisBijzondereRechtstoestand property.
     * 
     * @param value
     *     allowed object is
     *     {@link FunctionarisBijzondereRechtstoestandType }
     *     
     */
    public void setFunctionarisBijzondereRechtstoestand(FunctionarisBijzondereRechtstoestandType value) {
        this.functionarisBijzondereRechtstoestand = value;
    }

    /**
     * Gets the value of the gemachtigde property.
     * 
     * @return
     *     possible object is
     *     {@link GemachtigdeType }
     *     
     */
    public GemachtigdeType getGemachtigde() {
        return gemachtigde;
    }

    /**
     * Sets the value of the gemachtigde property.
     * 
     * @param value
     *     allowed object is
     *     {@link GemachtigdeType }
     *     
     */
    public void setGemachtigde(GemachtigdeType value) {
        this.gemachtigde = value;
    }

    /**
     * Gets the value of the overigeFunctionaris property.
     * 
     * @return
     *     possible object is
     *     {@link OverigeFunctionarisType }
     *     
     */
    public OverigeFunctionarisType getOverigeFunctionaris() {
        return overigeFunctionaris;
    }

    /**
     * Sets the value of the overigeFunctionaris property.
     * 
     * @param value
     *     allowed object is
     *     {@link OverigeFunctionarisType }
     *     
     */
    public void setOverigeFunctionaris(OverigeFunctionarisType value) {
        this.overigeFunctionaris = value;
    }

    /**
     * Gets the value of the publiekrechtelijkeFunctionaris property.
     * 
     * @return
     *     possible object is
     *     {@link PubliekrechtelijkeFunctionarisType }
     *     
     */
    public PubliekrechtelijkeFunctionarisType getPubliekrechtelijkeFunctionaris() {
        return publiekrechtelijkeFunctionaris;
    }

    /**
     * Sets the value of the publiekrechtelijkeFunctionaris property.
     * 
     * @param value
     *     allowed object is
     *     {@link PubliekrechtelijkeFunctionarisType }
     *     
     */
    public void setPubliekrechtelijkeFunctionaris(PubliekrechtelijkeFunctionarisType value) {
        this.publiekrechtelijkeFunctionaris = value;
    }

}
