//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.09.06 at 11:14:48 AM BST 
//


package com.example.howtodoinjava.schemas.school;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for MaatschappelijkeActiviteitResponseType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="MaatschappelijkeActiviteitResponseType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://schemas.kvk.nl/schemas/hrip/dataservice/2015/02}ResponseType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="product" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element ref="{http://schemas.kvk.nl/schemas/hrip/catalogus/2015/02}maatschappelijkeActiviteit"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MaatschappelijkeActiviteitResponseType", namespace = "http://schemas.kvk.nl/schemas/hrip/dataservice/2015/02", propOrder = {
    "product"
})
@XmlSeeAlso({
    InschrijvingResponseType.class
})
public class MaatschappelijkeActiviteitResponseType
    extends ResponseType
{

    protected MaatschappelijkeActiviteitResponseType.Product product;

    /**
     * Gets the value of the product property.
     * 
     * @return
     *     possible object is
     *     {@link MaatschappelijkeActiviteitResponseType.Product }
     *     
     */
    public MaatschappelijkeActiviteitResponseType.Product getProduct() {
        return product;
    }

    /**
     * Sets the value of the product property.
     * 
     * @param value
     *     allowed object is
     *     {@link MaatschappelijkeActiviteitResponseType.Product }
     *     
     */
    public void setProduct(MaatschappelijkeActiviteitResponseType.Product value) {
        this.product = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element ref="{http://schemas.kvk.nl/schemas/hrip/catalogus/2015/02}maatschappelijkeActiviteit"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "maatschappelijkeActiviteit"
    })
    public static class Product {

        @XmlElement(required = true)
        protected MaatschappelijkeActiviteitType maatschappelijkeActiviteit;

        /**
         * Gets the value of the maatschappelijkeActiviteit property.
         * 
         * @return
         *     possible object is
         *     {@link MaatschappelijkeActiviteitType }
         *     
         */
        public MaatschappelijkeActiviteitType getMaatschappelijkeActiviteit() {
            return maatschappelijkeActiviteit;
        }

        /**
         * Sets the value of the maatschappelijkeActiviteit property.
         * 
         * @param value
         *     allowed object is
         *     {@link MaatschappelijkeActiviteitType }
         *     
         */
        public void setMaatschappelijkeActiviteit(MaatschappelijkeActiviteitType value) {
            this.maatschappelijkeActiviteit = value;
        }

    }

}
