//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.09.06 at 10:42:47 PM BST 
//


package com.example.howtodoinjava.schemas.school;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for NoValue.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="NoValue"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="nietOndersteund"/&gt;
 *     &lt;enumeration value="nietGeautoriseerd"/&gt;
 *     &lt;enumeration value="geenWaarde"/&gt;
 *     &lt;enumeration value="waardeOnbekend"/&gt;
 *     &lt;enumeration value="vastgesteldOnbekend"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "NoValue")
@XmlEnum
public enum NoValue {

    @XmlEnumValue("nietOndersteund")
    NIET_ONDERSTEUND("nietOndersteund"),
    @XmlEnumValue("nietGeautoriseerd")
    NIET_GEAUTORISEERD("nietGeautoriseerd"),
    @XmlEnumValue("geenWaarde")
    GEEN_WAARDE("geenWaarde"),
    @XmlEnumValue("waardeOnbekend")
    WAARDE_ONBEKEND("waardeOnbekend"),
    @XmlEnumValue("vastgesteldOnbekend")
    VASTGESTELD_ONBEKEND("vastgesteldOnbekend");
    private final String value;

    NoValue(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static NoValue fromValue(String v) {
        for (NoValue c: NoValue.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
