//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.09.06 at 11:14:48 AM BST 
//


package com.example.howtodoinjava.schemas.school;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PostcodeType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PostcodeType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="cijfercombinatie"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;pattern value="[0-9]{4}"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="lettercombinatie" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;pattern value="[a-zA-Z]{2}"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PostcodeType", propOrder = {
    "cijfercombinatie",
    "lettercombinatie"
})
public class PostcodeType {

    @XmlElement(required = true)
    protected String cijfercombinatie;
    protected String lettercombinatie;

    /**
     * Gets the value of the cijfercombinatie property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCijfercombinatie() {
        return cijfercombinatie;
    }

    /**
     * Sets the value of the cijfercombinatie property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCijfercombinatie(String value) {
        this.cijfercombinatie = value;
    }

    /**
     * Gets the value of the lettercombinatie property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLettercombinatie() {
        return lettercombinatie;
    }

    /**
     * Sets the value of the lettercombinatie property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLettercombinatie(String value) {
        this.lettercombinatie = value;
    }

}
