//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.09.06 at 11:14:48 AM BST 
//


package com.example.howtodoinjava.schemas.school;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for RelatieType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RelatieType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://schemas.kvk.nl/schemas/hrip/catalogus/2015/02}MetExtraElementenMogenlijkheidType"&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RelatieType")
@XmlSeeAlso({
    PersoonRelatieType.class,
    NatuurlijkPersoonRelatieType.class,
    NietNatuurlijkPersoonRelatieType.class,
    FunctievervullingRelatieType.class,
    MaatschappelijkeActiviteitRelatieType.class,
    OndernemingRelatieType.class,
    VestigingRelatieType.class,
    VestigingenRelatieType.class,
    RelatieRegistratieType.class,
    DeponeringRelatieType.class,
    DeponeringNietNatuurlijkPersoonRelatieType.class
})
public abstract class RelatieType
    extends MetExtraElementenMogenlijkheidType
{


}
