//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.09.06 at 10:42:47 PM BST 
//


package com.example.howtodoinjava.schemas.school;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for VoortzettingRelatieRegistratieType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="VoortzettingRelatieRegistratieType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://schemas.kvk.nl/schemas/hrip/catalogus/2015/02}MaatschappelijkeActiviteitRelatieRegistratieType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="datumVoortzetting" type="{http://schemas.kvk.nl/schemas/hrip/catalogus/2015/02}DatumIncompleetType" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "VoortzettingRelatieRegistratieType", propOrder = {
    "datumVoortzetting"
})
public class VoortzettingRelatieRegistratieType
    extends MaatschappelijkeActiviteitRelatieRegistratieType
{

    protected String datumVoortzetting;

    /**
     * Gets the value of the datumVoortzetting property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDatumVoortzetting() {
        return datumVoortzetting;
    }

    /**
     * Sets the value of the datumVoortzetting property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDatumVoortzetting(String value) {
        this.datumVoortzetting = value;
    }

}
